language: ruby

rvm: 2.3.3

install: bundle install

script:
  - rake db:create
  - rake db:migrate
  - echo -n session=$ADVENT_OF_CODE_COOKIE > cookie.txt
  - rake spec
  - codeclimate-test-reporter
