language: ruby

rvm: 2.3.3

install: true #bundle install

script: echo $CODECLIMATE_REPO_TOKEN
#  - rake db:create
#  - rake db:migrate
#  - echo -n session=53616c7465645f5f91b1fce08411bbf3980eacc75a2906f35f32730aecaef31b90cf981bdd6a00fdf848593dc2389525 | tee cookie.txt
#  - rake spec
#  - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token:
      secure: SJwitEbknNR+HyPi837uSrOVOYxKNDzW9DLKwWc0+NTqOtuKlpjpFhArb7Eh6BAFhMRN1JIbQaLKl2GGsD8CK9Lh+eQBfO/YSg3k7I1SU8Tpbn0ALcgWnfxw03e+WWIYM9foIJepiGI12ERNVkoVgQoBtSmNccOLqCC1JX0q/bvf+KbG1snbbu5KxNNU3wgquakHmjAUUb+ZvtwT8eAbFBVWGUpomCIjLhpBu6sgkRsUCKZ28qIAyTk8idzn6PtpMyKJZfvJSyR3Bl3iAjg8IbB8CXl5m1lv6PXQaiUiRgk5GKsx7+PkxMBnOX10Z55dqsF8HM2mdJLF8ox8eIrscWKDdCqMc/5asU+CLSAlNw78e7oUc9JnxKFaHvNfPHiHjN3sru/jUP88ps81XU8MttbLxqNAwvEL75iHSTnR7r1bqq+nmsReZToG+mQcmzSYbdSKo4SdpcarimLvOyIXte07ZEvc/JVWay0PYbnMQM1P2SU8Rjxal2eF2fDsQlBSi+Qp5WPMzOUYOFbWCu6O20bJOy3bDpIc5EsWPaP1FGJaCboAaAL6STRV46nwk8yO3Uz/jNxyQHeRnDj2K3GdwUAgb6iqwH7AKHSJsW6/0ftckhcYMQHyveWRm5wHQEGPduCfBnQW1Ys6bv39wKEqmnhThmwxuVN55DBCFesy02U=
