language: ruby

rvm: 2.4.0

install: bundle install

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - echo -n session=$ADVENT_OF_CODE_COOKIE > cookie.txt
  - bundle exec rake spec
  - bundle exec codeclimate-test-reporter