language: ruby

rvm: 2.4.0

install: bundle install

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

script:
  - rake db:create
  - rake db:migrate
  - echo -n session=$ADVENT_OF_CODE_COOKIE > cookie.txt
  - rake spec
  - codeclimate-test-reporter