language: ruby

rvm: 2.3.3

install: bundle install

script:
  - rake db:create
  - rake db:migrate
  - echo -n session=53616c7465645f5f91b1fce08411bbf3980eacc75a2906f35f32730aecaef31b90cf981bdd6a00fdf848593dc2389525 | tee cookie.txt
  - rake spec
  - codeclimate-test-reporter
