language: ruby

rvm: 2.4.0

before_install:
  - openssl aes-256-cbc -K $encrypted_46cc5676755c_key -iv $encrypted_46cc5676755c_iv
    -in db/seeds/answers.json.enc -out db/seeds/answers.json -d

install: bundle install

sudo: required

services: postgresql

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - echo -n session=$ADVENT_OF_CODE_COOKIE > cookie.txt
  - bundle exec rake spec
  - bundle exec codeclimate-test-reporter