language: ruby

rvm: 2.4.0

before_install:
  - openssl aes-256-cbc -K $encrypted_46cc5676755c_key -iv $encrypted_46cc5676755c_iv
    -in db/seeds/answers.yml.enc -out db/seeds/answers.yml -d

gemfile:
  - Gemfile.ci

install: bundle install --with main ci

sudo: required

services: postgresql

matrix:
  fast_finish: true

script:
  - bundle exec rubocop -n --fail-level A -f fu -E -D -R -S
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:seed
  - bundle exec rake spec
  - bundle exec codeclimate-test-reporter