language: ruby

rvm: 2.4.0

install: bundle install

sudo: required

services: postgresql

before_install:
  - openssl aes-256-cbc -K $encrypted_46cc5676755c_key -iv $encrypted_46cc5676755c_iv
    -in lib/seeds/solutions.json.enc -out lib/seeds/solutions.json -d

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - echo -n session=$ADVENT_OF_CODE_COOKIE > cookie.txt
  - bundle exec rake spec
  - bundle exec codeclimate-test-reporter